<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260101000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the full Sulu database schema (initial baseline migration).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ac_activities (type VARCHAR(191) NOT NULL, context JSON NOT NULL, timestamp DATETIME NOT NULL, batch VARCHAR(191) DEFAULT NULL, payload JSON DEFAULT NULL, resourceKey VARCHAR(191) NOT NULL, resourceId VARCHAR(191) NOT NULL, resourceLocale VARCHAR(191) DEFAULT NULL, resourceWebspaceKey VARCHAR(191) DEFAULT NULL, resourceTitle VARCHAR(191) DEFAULT NULL, resourceTitleLocale VARCHAR(191) DEFAULT NULL, resourceSecurityContext VARCHAR(191) DEFAULT NULL, resourceSecurityObjectType VARCHAR(191) DEFAULT NULL, resourceSecurityObjectId VARCHAR(191) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, userId INT DEFAULT NULL, INDEX IDX_3EE015D064B64DCC (userId), INDEX timestamp_idx (timestamp), INDEX resourceKey_idx (resourceKey), INDEX resourceId_idx (resourceId), INDEX resourceSecurityContext_idx (resourceSecurityContext), INDEX resourceSecurityObjectType_idx (resourceSecurityObjectType), INDEX resourceSecurityObjectId_idx (resourceSecurityObjectId), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ar_article_dimension_content_additional_webspaces (name VARCHAR(31) NOT NULL, id INT AUTO_INCREMENT NOT NULL, article_dimension_content_id INT NOT NULL, INDEX IDX_3F9F33F37C1747D1 (article_dimension_content_id), INDEX idx_article_additional_webspace (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ar_article_dimension_contents (title VARCHAR(191) DEFAULT NULL, customizeWebspaceSettings TINYINT NOT NULL, id INT AUTO_INCREMENT NOT NULL, stage VARCHAR(15) NOT NULL, locale VARCHAR(15) DEFAULT NULL, ghostLocale VARCHAR(15) DEFAULT NULL, availableLocales JSON DEFAULT NULL, version INT NOT NULL, shadowLocale VARCHAR(15) DEFAULT NULL, shadowLocales JSON DEFAULT NULL, templateKey VARCHAR(31) DEFAULT NULL, templateData JSON NOT NULL, seoData JSON NOT NULL, seoNoIndex TINYINT NOT NULL, seoNoFollow TINYINT NOT NULL, seoHideInSitemap TINYINT NOT NULL, excerptData JSON NOT NULL, excerptSegment VARCHAR(255) DEFAULT NULL, mainWebspace VARCHAR(255) DEFAULT NULL, authored DATETIME DEFAULT NULL, lastModified DATETIME DEFAULT NULL, workflowPlace VARCHAR(31) DEFAULT NULL, workflowPublished DATETIME DEFAULT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, route_id INT DEFAULT NULL, articleUuid VARCHAR(36) NOT NULL, author_id INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_5674F7BF34ECB4E6 (route_id), INDEX IDX_5674F7BFAE39C518 (articleUuid), INDEX IDX_5674F7BFF675F31B (author_id), INDEX IDX_5674F7BFDBF11E1D (idUsersCreator), INDEX IDX_5674F7BF30D07CD5 (idUsersChanger), INDEX idx_ar_article_dimension_contents_dimension (stage, locale), INDEX idx_ar_article_dimension_contents_locale (locale), INDEX idx_ar_article_dimension_contents_stage (stage), INDEX idx_ar_article_dimension_contents_version (version), INDEX idx_ar_article_dimension_contents_stage_version_locale (stage, version, locale), INDEX idx_ar_article_dimension_contents_resource_lookup (articleUuid, stage, version, locale, ghostLocale), INDEX idx_ar_article_dimension_contents_template_key (templateKey), INDEX idx_ar_article_dimension_contents_resource_template_lookup (articleUuid, stage, version, locale, templateKey), INDEX idx_ar_article_dimension_contents_workflow_place (workflowPlace), INDEX idx_ar_article_dimension_contents_workflow_published (workflowPublished), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ar_article_dimension_content_excerpt_tags (article_dimension_content_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_B45854027C1747D1 (article_dimension_content_id), INDEX IDX_B4585402BAD26311 (tag_id), PRIMARY KEY (article_dimension_content_id, tag_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ar_article_dimension_content_excerpt_categories (article_dimension_content_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_971AE52D7C1747D1 (article_dimension_content_id), INDEX IDX_971AE52D12469DE2 (category_id), PRIMARY KEY (article_dimension_content_id, category_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ar_articles (uuid VARCHAR(36) NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_7F75CD17DBF11E1D (idUsersCreator), INDEX IDX_7F75CD1730D07CD5 (idUsersChanger), PRIMARY KEY (uuid)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ca_categories (category_key VARCHAR(191) DEFAULT NULL, default_locale VARCHAR(15) NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idCategoriesParent INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_3D85D789AF5206F3 (category_key), INDEX IDX_3D85D78937A3C3B1 (idCategoriesParent), INDEX IDX_3D85D789DBF11E1D (idUsersCreator), INDEX IDX_3D85D78930D07CD5 (idUsersChanger), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ca_category_translation_medias (position INT DEFAULT 0 NOT NULL, id INT AUTO_INCREMENT NOT NULL, idCategoryTranslations INT NOT NULL, idMedia INT NOT NULL, INDEX IDX_39FC41BA17CA14DA (idCategoryTranslations), INDEX IDX_39FC41BA7DE8E211 (idMedia), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ca_category_translations (translation VARCHAR(255) NOT NULL, locale VARCHAR(15) NOT NULL, description LONGTEXT DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idCategories INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_5DCED5E3B8075882 (idCategories), INDEX IDX_5DCED5E3DBF11E1D (idUsersCreator), INDEX IDX_5DCED5E330D07CD5 (idUsersChanger), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ca_keywords (locale VARCHAR(15) NOT NULL, keyword VARCHAR(191) NOT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_FE02CA0BDBF11E1D (idUsersCreator), INDEX IDX_FE02CA0B30D07CD5 (idUsersChanger), INDEX IDX_FE02CA0B5A93713B (keyword), UNIQUE INDEX unique_idx (keyword, locale), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ca_category_translation_keywords (idKeywords INT NOT NULL, idCategoryTranslations INT NOT NULL, INDEX IDX_D15FBE37F9FC9F05 (idKeywords), INDEX IDX_D15FBE3717CA14DA (idCategoryTranslations), PRIMARY KEY (idKeywords, idCategoryTranslations)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_addresses (main TINYINT NOT NULL, id INT AUTO_INCREMENT NOT NULL, idAddresses INT NOT NULL, idAccounts INT NOT NULL, INDEX IDX_4165FE4893205E40 (idAddresses), INDEX IDX_4165FE48996BB4F7 (idAccounts), UNIQUE INDEX UNIQ_4165FE4893205E40996BB4F7 (idAddresses, idAccounts), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_contacts (main TINYINT NOT NULL, id INT AUTO_INCREMENT NOT NULL, idPositions INT DEFAULT NULL, idContacts INT NOT NULL, idAccounts INT NOT NULL, INDEX IDX_28C6CA0E2A75CE2A (idPositions), INDEX IDX_28C6CA0E60E33F28 (idContacts), INDEX IDX_28C6CA0E996BB4F7 (idAccounts), UNIQUE INDEX UNIQ_28C6CA0E60E33F28996BB4F7 (idContacts, idAccounts), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_accounts (lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, name VARCHAR(150) NOT NULL, externalId VARCHAR(255) DEFAULT NULL, number VARCHAR(255) DEFAULT NULL, corporation VARCHAR(255) DEFAULT NULL, note LONGTEXT DEFAULT NULL, uid VARCHAR(50) DEFAULT NULL, registerNumber VARCHAR(255) DEFAULT NULL, placeOfJurisdiction VARCHAR(255) DEFAULT NULL, mainEmail VARCHAR(255) DEFAULT NULL, mainPhone VARCHAR(255) DEFAULT NULL, mainFax VARCHAR(255) DEFAULT NULL, mainUrl VARCHAR(255) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idContactsMain INT DEFAULT NULL, idAccountsParent INT DEFAULT NULL, logo INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_805CD14A6D4A8651 (idContactsMain), INDEX IDX_805CD14AC9171171 (idAccountsParent), INDEX IDX_805CD14AE48E9A13 (logo), INDEX IDX_805CD14ADBF11E1D (idUsersCreator), INDEX IDX_805CD14A30D07CD5 (idUsersChanger), INDEX IDX_805CD14A5E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_urls (idAccounts INT NOT NULL, idUrls INT NOT NULL, INDEX IDX_ADF18382996BB4F7 (idAccounts), INDEX IDX_ADF183825969693F (idUrls), PRIMARY KEY (idAccounts, idUrls)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_phones (idAccounts INT NOT NULL, idPhones INT NOT NULL, INDEX IDX_918DA964996BB4F7 (idAccounts), INDEX IDX_918DA9648039866F (idPhones), PRIMARY KEY (idAccounts, idPhones)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_emails (idAccounts INT NOT NULL, idEmails INT NOT NULL, INDEX IDX_3E246FC3996BB4F7 (idAccounts), INDEX IDX_3E246FC32F9040C8 (idEmails), PRIMARY KEY (idAccounts, idEmails)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_notes (idAccounts INT NOT NULL, idNotes INT NOT NULL, INDEX IDX_A3FBB24A996BB4F7 (idAccounts), INDEX IDX_A3FBB24A16DFE591 (idNotes), PRIMARY KEY (idAccounts, idNotes)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_faxes (idAccounts INT NOT NULL, idFaxes INT NOT NULL, INDEX IDX_7A4E77DC996BB4F7 (idAccounts), INDEX IDX_7A4E77DCCF6A2007 (idFaxes), PRIMARY KEY (idAccounts, idFaxes)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_social_media_profiles (idAccounts INT NOT NULL, idSocialMediaProfiles INT NOT NULL, INDEX IDX_E06F75F5996BB4F7 (idAccounts), INDEX IDX_E06F75F5573F8344 (idSocialMediaProfiles), PRIMARY KEY (idAccounts, idSocialMediaProfiles)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_bank_accounts (idAccounts INT NOT NULL, idBankAccounts INT NOT NULL, INDEX IDX_C873A532996BB4F7 (idAccounts), INDEX IDX_C873A53237FCD1D8 (idBankAccounts), PRIMARY KEY (idAccounts, idBankAccounts)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_categories (idAccounts INT NOT NULL, idCategories INT NOT NULL, INDEX IDX_B60E9510996BB4F7 (idAccounts), INDEX IDX_B60E9510B8075882 (idCategories), PRIMARY KEY (idAccounts, idCategories)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_medias (idAccounts INT NOT NULL, idMedias INT NOT NULL, INDEX IDX_60772810996BB4F7 (idAccounts), INDEX IDX_6077281071C3071B (idMedias), PRIMARY KEY (idAccounts, idMedias)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_account_tags (idAccounts INT NOT NULL, idTags INT NOT NULL, INDEX IDX_E8D92005996BB4F7 (idAccounts), INDEX IDX_E8D920051C41CAB8 (idTags), PRIMARY KEY (idAccounts, idTags)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_address_types (name VARCHAR(60) NOT NULL, id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_addresses (title VARCHAR(250) DEFAULT NULL, primaryAddress TINYINT DEFAULT NULL, deliveryAddress TINYINT DEFAULT NULL, billingAddress TINYINT DEFAULT NULL, street VARCHAR(150) DEFAULT NULL, number VARCHAR(60) DEFAULT NULL, addition VARCHAR(60) DEFAULT NULL, zip VARCHAR(60) DEFAULT NULL, city VARCHAR(60) DEFAULT NULL, state VARCHAR(60) DEFAULT NULL, countryCode VARCHAR(5) DEFAULT NULL, postboxNumber VARCHAR(100) DEFAULT NULL, postboxPostcode VARCHAR(100) DEFAULT NULL, postboxCity VARCHAR(100) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, note LONGTEXT DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, idAdressTypes INT NOT NULL, INDEX IDX_26E9A6142A37021A (idAdressTypes), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_bank_account (bankName VARCHAR(150) DEFAULT NULL, bic VARCHAR(100) DEFAULT NULL, iban VARCHAR(100) NOT NULL, public TINYINT NOT NULL, id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_addresses (main TINYINT NOT NULL, id INT AUTO_INCREMENT NOT NULL, idAddresses INT NOT NULL, idContacts INT NOT NULL, INDEX IDX_DEE056893205E40 (idAddresses), INDEX IDX_DEE056860E33F28 (idContacts), UNIQUE INDEX UNIQ_DEE056893205E4060E33F28 (idAddresses, idContacts), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_locales (locale VARCHAR(60) NOT NULL, id INT AUTO_INCREMENT NOT NULL, idContacts INT NOT NULL, INDEX IDX_31E5672760E33F28 (idContacts), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_titles (title VARCHAR(60) NOT NULL, id INT AUTO_INCREMENT NOT NULL, UNIQUE INDEX UNIQ_4463FC02B36786B (title), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contacts (firstName VARCHAR(60) NOT NULL, middleName VARCHAR(60) DEFAULT NULL, lastName VARCHAR(60) NOT NULL, birthday DATE DEFAULT NULL, salutation VARCHAR(255) DEFAULT NULL, formOfAddress INT DEFAULT NULL, newsletter TINYINT DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, note LONGTEXT DEFAULT NULL, mainEmail VARCHAR(255) DEFAULT NULL, mainPhone VARCHAR(255) DEFAULT NULL, mainFax VARCHAR(255) DEFAULT NULL, mainUrl VARCHAR(255) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idTitles INT DEFAULT NULL, avatar INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_79D45A95A254E939 (idTitles), INDEX IDX_79D45A951677722F (avatar), INDEX IDX_79D45A95DBF11E1D (idUsersCreator), INDEX IDX_79D45A9530D07CD5 (idUsersChanger), INDEX IDX_79D45A952392A156 (firstName), INDEX IDX_79D45A9591161A88 (lastName), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_urls (idContacts INT NOT NULL, idUrls INT NOT NULL, INDEX IDX_99D86D760E33F28 (idContacts), INDEX IDX_99D86D75969693F (idUrls), PRIMARY KEY (idContacts, idUrls)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_notes (idContacts INT NOT NULL, idNotes INT NOT NULL, INDEX IDX_B85E7B3460E33F28 (idContacts), INDEX IDX_B85E7B3416DFE591 (idNotes), PRIMARY KEY (idContacts, idNotes)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_emails (idContacts INT NOT NULL, idEmails INT NOT NULL, INDEX IDX_8982963160E33F28 (idContacts), INDEX IDX_898296312F9040C8 (idEmails), PRIMARY KEY (idContacts, idEmails)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_phones (idContacts INT NOT NULL, idPhones INT NOT NULL, INDEX IDX_262B509660E33F28 (idContacts), INDEX IDX_262B50968039866F (idPhones), PRIMARY KEY (idContacts, idPhones)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_faxes (idContacts INT NOT NULL, idFaxes INT NOT NULL, INDEX IDX_61EBBEA260E33F28 (idContacts), INDEX IDX_61EBBEA2CF6A2007 (idFaxes), PRIMARY KEY (idContacts, idFaxes)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_social_media_profiles (idContacts INT NOT NULL, idSocialMediaProfiles INT NOT NULL, INDEX IDX_74FF4CC060E33F28 (idContacts), INDEX IDX_74FF4CC0573F8344 (idSocialMediaProfiles), PRIMARY KEY (idContacts, idSocialMediaProfiles)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_bank_accounts (idContacts INT NOT NULL, idBankAccounts INT NOT NULL, INDEX IDX_76CDDA0660E33F28 (idContacts), INDEX IDX_76CDDA0637FCD1D8 (idBankAccounts), PRIMARY KEY (idContacts, idBankAccounts)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_medias (idContacts INT NOT NULL, idMedias INT NOT NULL, INDEX IDX_D7D1D1E260E33F28 (idContacts), INDEX IDX_D7D1D1E271C3071B (idMedias), PRIMARY KEY (idContacts, idMedias)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_categories (idContacts INT NOT NULL, idCategories INT NOT NULL, INDEX IDX_8D2C3E2360E33F28 (idContacts), INDEX IDX_8D2C3E23B8075882 (idCategories), PRIMARY KEY (idContacts, idCategories)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_contact_tags (idContacts INT NOT NULL, idTags INT NOT NULL, INDEX IDX_4CB5255060E33F28 (idContacts), INDEX IDX_4CB525501C41CAB8 (idTags), PRIMARY KEY (idContacts, idTags)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_email_types (name VARCHAR(60) NOT NULL, id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_emails (email VARCHAR(60) NOT NULL, id INT AUTO_INCREMENT NOT NULL, idEmailTypes INT NOT NULL, INDEX IDX_A2F2CB77D816E840 (idEmailTypes), INDEX IDX_A2F2CB77E7927C74 (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_fax_types (name VARCHAR(60) NOT NULL, id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_faxes (fax VARCHAR(255) NOT NULL, id INT AUTO_INCREMENT NOT NULL, idFaxTypes INT NOT NULL, INDEX IDX_A5EC6A18B466C5DA (idFaxTypes), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_notes (value LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_phone_types (name VARCHAR(60) NOT NULL, id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_phones (phone VARCHAR(60) NOT NULL, id INT AUTO_INCREMENT NOT NULL, idPhoneTypes INT NOT NULL, INDEX IDX_D5B0DD0A4249AD7 (idPhoneTypes), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_positions (position VARCHAR(191) NOT NULL, id INT AUTO_INCREMENT NOT NULL, UNIQUE INDEX UNIQ_9FBC367E462CE4F5 (position), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_social_media_profile_types (name VARCHAR(100) NOT NULL, id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_social_media_profiles (username VARCHAR(255) NOT NULL, id INT AUTO_INCREMENT NOT NULL, idSocialMediaTypes INT NOT NULL, INDEX IDX_DF585BFBB5BEA95F (idSocialMediaTypes), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_url_types (name VARCHAR(60) NOT NULL, id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE co_urls (url VARCHAR(255) NOT NULL, id INT AUTO_INCREMENT NOT NULL, idUrlTypes INT NOT NULL, INDEX IDX_6F03842E882335CC (idUrlTypes), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE cu_custom_url (title VARCHAR(255) NOT NULL, published TINYINT NOT NULL, base_domain VARCHAR(255) NOT NULL, webspace VARCHAR(255) NOT NULL, domain_parts JSON NOT NULL, target_document VARCHAR(255) DEFAULT NULL, target_locale VARCHAR(255) NOT NULL, canonical TINYINT NOT NULL, redirect TINYINT NOT NULL, no_follow TINYINT NOT NULL, no_index TINYINT NOT NULL, uuid VARCHAR(36) NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_51A7F98D2B36786B (title), INDEX IDX_51A7F98DDBF11E1D (idUsersCreator), INDEX IDX_51A7F98D30D07CD5 (idUsersChanger), INDEX IDX_51A7F98DB055BCD4 (webspace), PRIMARY KEY (uuid)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE cu_custom_url_route (path VARCHAR(255) NOT NULL, history TINYINT DEFAULT 0 NOT NULL, uuid VARCHAR(36) NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, customUrl VARCHAR(36) NOT NULL, target_route_uuid VARCHAR(36) DEFAULT NULL, INDEX IDX_D2349CF4CB30A644 (customUrl), INDEX IDX_D2349CF44ED689B2 (target_route_uuid), INDEX custom_url_route_history_idx (history), UNIQUE INDEX cu_custom_url_route_unique (path), PRIMARY KEY (uuid)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE me_collection_meta (title VARCHAR(191) NOT NULL, description LONGTEXT DEFAULT NULL, locale VARCHAR(15) NOT NULL, id INT AUTO_INCREMENT NOT NULL, idCollections INT NOT NULL, INDEX IDX_F8D5E71693782C96 (idCollections), INDEX IDX_F8D5E7162B36786B (title), INDEX IDX_F8D5E7164180C698 (locale), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE me_collection_types (name VARCHAR(255) NOT NULL, collection_type_key VARCHAR(191) DEFAULT NULL, description LONGTEXT DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, UNIQUE INDEX UNIQ_FB78DFB179078378 (collection_type_key), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE me_collections (style VARCHAR(255) DEFAULT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, collection_key VARCHAR(191) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idCollectionsMetaDefault INT DEFAULT NULL, idCollectionTypes INT NOT NULL, idCollectionsParent INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_F0D4887221904CD (collection_key), UNIQUE INDEX UNIQ_F0D4887CFA3F467 (idCollectionsMetaDefault), INDEX IDX_F0D4887E67924D6 (idCollectionTypes), INDEX IDX_F0D4887A4F2DCF8 (idCollectionsParent), INDEX IDX_F0D4887DBF11E1D (idUsersCreator), INDEX IDX_F0D488730D07CD5 (idUsersChanger), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE me_file_version_meta (title VARCHAR(191) NOT NULL, description LONGTEXT DEFAULT NULL, copyright LONGTEXT DEFAULT NULL, credits LONGTEXT DEFAULT NULL, locale VARCHAR(15) NOT NULL, id INT AUTO_INCREMENT NOT NULL, idFileVersions INT NOT NULL, INDEX IDX_AD44B0AD911ADE33 (idFileVersions), INDEX IDX_AD44B0AD2B36786B (title), INDEX IDX_AD44B0AD4180C698 (locale), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE me_file_versions (name VARCHAR(191) NOT NULL, version INT NOT NULL, subVersion INT DEFAULT 0 NOT NULL, size INT NOT NULL, downloadCounter INT DEFAULT 0 NOT NULL, storageOptions LONGTEXT DEFAULT NULL, mimeType VARCHAR(191) DEFAULT NULL, properties VARCHAR(1000) DEFAULT NULL, focusPointX INT DEFAULT NULL, focusPointY INT DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idFileVersionsMetaDefault INT DEFAULT NULL, idFiles INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_7B6E89456B801096 (idFileVersionsMetaDefault), INDEX IDX_7B6E894511F10344 (idFiles), INDEX IDX_7B6E8945DBF11E1D (idUsersCreator), INDEX IDX_7B6E894530D07CD5 (idUsersChanger), INDEX IDX_7B6E8945D8F2A087 (mimeType), INDEX IDX_7B6E8945F7C0246A (size), INDEX IDX_7B6E8945BF1CD3C3 (version), INDEX IDX_7B6E89455E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE me_file_version_tags (idFileVersions INT NOT NULL, idTags INT NOT NULL, INDEX IDX_150A30BE911ADE33 (idFileVersions), INDEX IDX_150A30BE1C41CAB8 (idTags), PRIMARY KEY (idFileVersions, idTags)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE me_file_version_categories (idFileVersions INT NOT NULL, idCategories INT NOT NULL, INDEX IDX_2F1E17D0911ADE33 (idFileVersions), INDEX IDX_2F1E17D0B8075882 (idCategories), PRIMARY KEY (idFileVersions, idCategories)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE me_files (version INT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idMedia INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_CA8D04277DE8E211 (idMedia), INDEX IDX_CA8D0427DBF11E1D (idUsersCreator), INDEX IDX_CA8D042730D07CD5 (idUsersChanger), INDEX IDX_CA8D0427BF1CD3C3 (version), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE me_format_options (crop_x INT NOT NULL, crop_y INT NOT NULL, crop_width INT NOT NULL, crop_height INT NOT NULL, format_key VARCHAR(191) NOT NULL, fileVersion INT NOT NULL, INDEX IDX_6D25443B31852B63 (fileVersion), PRIMARY KEY (format_key, fileVersion)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE me_media (type VARCHAR(10) NOT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idPreviewImage INT DEFAULT NULL, idCollections INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_A694E572D1EB44DE (idPreviewImage), INDEX IDX_A694E57293782C96 (idCollections), INDEX IDX_A694E572DBF11E1D (idUsersCreator), INDEX IDX_A694E57230D07CD5 (idUsersChanger), INDEX IDX_A694E572A3F33DFA (changed), INDEX IDX_A694E572B23DB7B8 (created), INDEX IDX_A694E5728CDE5729 (type), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE pa_page_dimension_content_navigation_contexts (name VARCHAR(31) NOT NULL, id INT AUTO_INCREMENT NOT NULL, page_dimension_content_id INT NOT NULL, INDEX IDX_4C5FD8F767C2CFD5 (page_dimension_content_id), INDEX idx_page_navigation_context (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE pa_page_dimension_contents (title VARCHAR(191) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, stage VARCHAR(15) NOT NULL, locale VARCHAR(15) DEFAULT NULL, ghostLocale VARCHAR(15) DEFAULT NULL, availableLocales JSON DEFAULT NULL, version INT NOT NULL, shadowLocale VARCHAR(15) DEFAULT NULL, shadowLocales JSON DEFAULT NULL, templateKey VARCHAR(31) DEFAULT NULL, templateData JSON NOT NULL, seoData JSON NOT NULL, seoNoIndex TINYINT NOT NULL, seoNoFollow TINYINT NOT NULL, seoHideInSitemap TINYINT NOT NULL, excerptData JSON NOT NULL, excerptSegment VARCHAR(255) DEFAULT NULL, authored DATETIME DEFAULT NULL, lastModified DATETIME DEFAULT NULL, workflowPlace VARCHAR(31) DEFAULT NULL, workflowPublished DATETIME DEFAULT NULL, linkProvider VARCHAR(32) DEFAULT NULL, linkData JSON DEFAULT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, route_id INT DEFAULT NULL, pageUuid VARCHAR(36) NOT NULL, author_id INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_209A42C034ECB4E6 (route_id), INDEX IDX_209A42C0F099EEF3 (pageUuid), INDEX IDX_209A42C0F675F31B (author_id), INDEX IDX_209A42C0DBF11E1D (idUsersCreator), INDEX IDX_209A42C030D07CD5 (idUsersChanger), INDEX idx_pa_page_dimension_contents_dimension (stage, locale), INDEX idx_pa_page_dimension_contents_locale (locale), INDEX idx_pa_page_dimension_contents_stage (stage), INDEX idx_pa_page_dimension_contents_version (version), INDEX idx_pa_page_dimension_contents_stage_version_locale (stage, version, locale), INDEX idx_pa_page_dimension_contents_resource_lookup (pageUuid, stage, version, locale, ghostLocale), INDEX idx_pa_page_dimension_contents_template_key (templateKey), INDEX idx_pa_page_dimension_contents_resource_template_lookup (pageUuid, stage, version, locale, templateKey), INDEX idx_pa_page_dimension_contents_workflow_place (workflowPlace), INDEX idx_pa_page_dimension_contents_workflow_published (workflowPublished), INDEX idx_pa_page_dimension_contents_link_provider (linkProvider), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE pa_page_dimension_content_excerpt_tags (page_dimension_content_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_66C81FDB67C2CFD5 (page_dimension_content_id), INDEX IDX_66C81FDBBAD26311 (tag_id), PRIMARY KEY (page_dimension_content_id, tag_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE pa_page_dimension_content_excerpt_categories (page_dimension_content_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_BE45C16867C2CFD5 (page_dimension_content_id), INDEX IDX_BE45C16812469DE2 (category_id), PRIMARY KEY (page_dimension_content_id, category_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE pa_pages (webspaceKey VARCHAR(31) NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, uuid VARCHAR(36) NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, parent_id VARCHAR(36) DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_FF3DA1E2727ACA70 (parent_id), INDEX IDX_FF3DA1E2DBF11E1D (idUsersCreator), INDEX IDX_FF3DA1E230D07CD5 (idUsersChanger), PRIMARY KEY (uuid)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE pr_preview_links (token VARCHAR(12) NOT NULL, resourceKey VARCHAR(255) NOT NULL, resourceId VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, options JSON NOT NULL, visitCount INT NOT NULL, lastVisit DATETIME DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, UNIQUE INDEX UNIQ_EFB5DBF25F37A13B (token), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE re_references (resourceKey VARCHAR(191) NOT NULL, resourceId VARCHAR(191) NOT NULL, referenceResourceKey VARCHAR(191) NOT NULL, referenceResourceId VARCHAR(191) NOT NULL, referenceLocale VARCHAR(15) DEFAULT NULL, referenceRouterAttributes JSON NOT NULL, referenceTitle VARCHAR(191) NOT NULL, referenceProperty VARCHAR(191) NOT NULL, referenceContext VARCHAR(16) NOT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, INDEX resource_idx (resourceKey, resourceId), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ro_routes (webspace VARCHAR(31) DEFAULT NULL, locale VARCHAR(15) NOT NULL, slug VARCHAR(144) NOT NULL, resource_key VARCHAR(32) NOT NULL, resource_id VARCHAR(70) NOT NULL, id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, INDEX IDX_671DB7A4727ACA70 (parent_id), INDEX ro_routes_resource_idx (locale, resource_key, resource_id), UNIQUE INDEX ro_routes_unique (webspace, locale, slug), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE se_access_controls (permissions SMALLINT NOT NULL, entityId VARCHAR(36) NOT NULL, entityClass VARCHAR(191) NOT NULL, entityIdInteger INT DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, idRoles INT NOT NULL, INDEX IDX_C526DC52F62829FC (entityId), INDEX IDX_C526DC523963FFAB (entityClass), INDEX IDX_C526DC524473BB7A (entityIdInteger), INDEX IDX_C526DC52A1FA6DDA (idRoles), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE se_permissions (context VARCHAR(191) NOT NULL, permissions SMALLINT NOT NULL, id INT AUTO_INCREMENT NOT NULL, idRoles INT DEFAULT NULL, INDEX IDX_5CEC3EEAA1FA6DDA (idRoles), UNIQUE INDEX UNIQ_5CEC3EEAE25D857EA1FA6DDA (context, idRoles), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE se_role_settings (settingKey VARCHAR(191) NOT NULL, value JSON NOT NULL, id INT AUTO_INCREMENT NOT NULL, roleId INT DEFAULT NULL, INDEX IDX_DAD1C8CBB8C2FD88 (roleId), INDEX IDX_DAD1C8CB3AA9950B (settingKey), UNIQUE INDEX UNIQ_DAD1C8CB3AA9950BB8C2FD88 (settingKey, roleId), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE se_roles (name VARCHAR(60) NOT NULL, role_key VARCHAR(60) DEFAULT NULL, securitySystem VARCHAR(60) NOT NULL, anonymous TINYINT DEFAULT 0 NOT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_13B749A05E237E06 (name), UNIQUE INDEX UNIQ_13B749A03EF22FDB (role_key), INDEX IDX_13B749A0DBF11E1D (idUsersCreator), INDEX IDX_13B749A030D07CD5 (idUsersChanger), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE se_user_roles (locale LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, idUsers INT DEFAULT NULL, idRoles INT DEFAULT NULL, INDEX IDX_E48BD9DB347E6F4 (idUsers), INDEX IDX_E48BD9DBA1FA6DDA (idRoles), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE se_user_settings (settingsValue LONGTEXT NOT NULL, settingsKey VARCHAR(150) NOT NULL, idUsers INT NOT NULL, INDEX IDX_108FCAFA347E6F4 (idUsers), PRIMARY KEY (settingsKey, idUsers)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE se_user_two_factors (method VARCHAR(12) DEFAULT NULL, options LONGTEXT DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, idUsers INT NOT NULL, UNIQUE INDEX UNIQ_732E8321347E6F4 (idUsers), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE se_users (username VARCHAR(60) NOT NULL, password VARCHAR(128) NOT NULL, locale VARCHAR(60) NOT NULL, salt VARCHAR(60) NOT NULL, locked TINYINT DEFAULT 0 NOT NULL, enabled TINYINT DEFAULT 1 NOT NULL, lastLogin DATETIME DEFAULT NULL, confirmationKey VARCHAR(128) DEFAULT NULL, passwordResetToken VARCHAR(80) DEFAULT NULL, passwordResetTokenExpiresAt DATETIME DEFAULT NULL, passwordResetTokenEmailsSent INT DEFAULT 0, privateKey VARCHAR(2000) DEFAULT NULL, apiKey VARCHAR(128) DEFAULT NULL, email VARCHAR(191) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idContacts INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_B10AC28EF85E0677 (username), UNIQUE INDEX UNIQ_B10AC28EADC1CD13 (passwordResetToken), UNIQUE INDEX UNIQ_B10AC28EE7927C74 (email), UNIQUE INDEX UNIQ_B10AC28E60E33F28 (idContacts), INDEX IDX_B10AC28EDBF11E1D (idUsersCreator), INDEX IDX_B10AC28E30D07CD5 (idUsersChanger), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE sn_snippet_area (webspace_key VARCHAR(255) NOT NULL, area_key VARCHAR(255) NOT NULL, uuid VARCHAR(255) NOT NULL, idSnippet VARCHAR(36) DEFAULT NULL, INDEX IDX_8C978EE186A5E727 (idSnippet), PRIMARY KEY (uuid)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE sn_snippet_dimension_contents (title VARCHAR(191) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, stage VARCHAR(15) NOT NULL, locale VARCHAR(15) DEFAULT NULL, ghostLocale VARCHAR(15) DEFAULT NULL, availableLocales JSON DEFAULT NULL, version INT NOT NULL, templateKey VARCHAR(31) DEFAULT NULL, templateData JSON NOT NULL, excerptSegment VARCHAR(255) DEFAULT NULL, workflowPlace VARCHAR(31) DEFAULT NULL, workflowPublished DATETIME DEFAULT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, snippetUuid VARCHAR(36) NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_46D6814477F33FFB (snippetUuid), INDEX IDX_46D68144DBF11E1D (idUsersCreator), INDEX IDX_46D6814430D07CD5 (idUsersChanger), INDEX idx_sn_snippet_dimension_contents_dimension (stage, locale), INDEX idx_sn_snippet_dimension_contents_locale (locale), INDEX idx_sn_snippet_dimension_contents_stage (stage), INDEX idx_sn_snippet_dimension_contents_version (version), INDEX idx_sn_snippet_dimension_contents_stage_version_locale (stage, version, locale), INDEX idx_sn_snippet_dimension_contents_resource_lookup (snippetUuid, stage, version, locale, ghostLocale), INDEX idx_sn_snippet_dimension_contents_template_key (templateKey), INDEX idx_sn_snippet_dimension_contents_resource_template_lookup (snippetUuid, stage, version, locale, templateKey), INDEX idx_sn_snippet_dimension_contents_workflow_place (workflowPlace), INDEX idx_sn_snippet_dimension_contents_workflow_published (workflowPublished), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE sn_snippet_dimension_content_excerpt_tags (snippet_dimension_content_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_96BD1E357891499D (snippet_dimension_content_id), INDEX IDX_96BD1E35BAD26311 (tag_id), PRIMARY KEY (snippet_dimension_content_id, tag_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE sn_snippet_dimension_content_excerpt_categories (snippet_dimension_content_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_464EB1547891499D (snippet_dimension_content_id), INDEX IDX_464EB15412469DE2 (category_id), PRIMARY KEY (snippet_dimension_content_id, category_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE sn_snippets (uuid VARCHAR(36) NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_E68115CFDBF11E1D (idUsersCreator), INDEX IDX_E68115CF30D07CD5 (idUsersChanger), PRIMARY KEY (uuid)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ta_tags (name VARCHAR(191) NOT NULL, id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_B258E4995E237E06 (name), INDEX IDX_B258E499DBF11E1D (idUsersCreator), INDEX IDX_B258E49930D07CD5 (idUsersChanger), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE tr_trash_item_translations (locale VARCHAR(191) DEFAULT NULL, title VARCHAR(191) NOT NULL, id INT AUTO_INCREMENT NOT NULL, trashItemId INT NOT NULL, INDEX IDX_8264DAF45C8D7CA (trashItemId), UNIQUE INDEX UNIQ_8264DAF45C8D7CA4180C698 (trashItemId, locale), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE tr_trash_items (resourceKey VARCHAR(191) NOT NULL, resourceId VARCHAR(191) NOT NULL, restoreData JSON NOT NULL, restoreType VARCHAR(191) DEFAULT NULL, restoreOptions JSON NOT NULL, resourceSecurityContext VARCHAR(191) DEFAULT NULL, resourceSecurityObjectType VARCHAR(191) DEFAULT NULL, resourceSecurityObjectId VARCHAR(191) DEFAULT NULL, storeTimestamp DATETIME NOT NULL, defaultLocale VARCHAR(191) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, userId INT DEFAULT NULL, INDEX IDX_102989B64B64DCC (userId), INDEX IDX_102989B5DAEB55C8CF57CB1 (resourceKey, resourceId), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE we_analytics (title VARCHAR(255) NOT NULL, webspace_key VARCHAR(191) NOT NULL, all_domains TINYINT NOT NULL, content JSON NOT NULL, type VARCHAR(60) NOT NULL, id INT AUTO_INCREMENT NOT NULL, INDEX IDX_4E50BB8D1640EFD3 (all_domains), INDEX IDX_4E50BB8DAE248174 (webspace_key), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE we_analytics_domains (analytics INT NOT NULL, domain INT NOT NULL, INDEX IDX_F9323B6EEAC2E688 (analytics), INDEX IDX_F9323B6EA7A91E0B (domain), PRIMARY KEY (analytics, domain)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE we_domains (url VARCHAR(191) NOT NULL, environment VARCHAR(10) NOT NULL, id INT AUTO_INCREMENT NOT NULL, INDEX IDX_7CFAB3F5F47645AE (url), INDEX IDX_7CFAB3F54626DE22 (environment), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE ac_activities ADD CONSTRAINT FK_3EE015D064B64DCC FOREIGN KEY (userId) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ar_article_dimension_content_additional_webspaces ADD CONSTRAINT FK_3F9F33F37C1747D1 FOREIGN KEY (article_dimension_content_id) REFERENCES ar_article_dimension_contents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ar_article_dimension_contents ADD CONSTRAINT FK_5674F7BF34ECB4E6 FOREIGN KEY (route_id) REFERENCES ro_routes (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ar_article_dimension_contents ADD CONSTRAINT FK_5674F7BFAE39C518 FOREIGN KEY (articleUuid) REFERENCES ar_articles (uuid) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ar_article_dimension_contents ADD CONSTRAINT FK_5674F7BFF675F31B FOREIGN KEY (author_id) REFERENCES co_contacts (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ar_article_dimension_contents ADD CONSTRAINT FK_5674F7BFDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ar_article_dimension_contents ADD CONSTRAINT FK_5674F7BF30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ar_article_dimension_content_excerpt_tags ADD CONSTRAINT FK_B45854027C1747D1 FOREIGN KEY (article_dimension_content_id) REFERENCES ar_article_dimension_contents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ar_article_dimension_content_excerpt_tags ADD CONSTRAINT FK_B4585402BAD26311 FOREIGN KEY (tag_id) REFERENCES ta_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ar_article_dimension_content_excerpt_categories ADD CONSTRAINT FK_971AE52D7C1747D1 FOREIGN KEY (article_dimension_content_id) REFERENCES ar_article_dimension_contents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ar_article_dimension_content_excerpt_categories ADD CONSTRAINT FK_971AE52D12469DE2 FOREIGN KEY (category_id) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ar_articles ADD CONSTRAINT FK_7F75CD17DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ar_articles ADD CONSTRAINT FK_7F75CD1730D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_categories ADD CONSTRAINT FK_3D85D78937A3C3B1 FOREIGN KEY (idCategoriesParent) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_categories ADD CONSTRAINT FK_3D85D789DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_categories ADD CONSTRAINT FK_3D85D78930D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_category_translation_medias ADD CONSTRAINT FK_39FC41BA17CA14DA FOREIGN KEY (idCategoryTranslations) REFERENCES ca_category_translations (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_category_translation_medias ADD CONSTRAINT FK_39FC41BA7DE8E211 FOREIGN KEY (idMedia) REFERENCES me_media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_category_translations ADD CONSTRAINT FK_5DCED5E3B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_category_translations ADD CONSTRAINT FK_5DCED5E3DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_category_translations ADD CONSTRAINT FK_5DCED5E330D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_keywords ADD CONSTRAINT FK_FE02CA0BDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_keywords ADD CONSTRAINT FK_FE02CA0B30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_category_translation_keywords ADD CONSTRAINT FK_D15FBE37F9FC9F05 FOREIGN KEY (idKeywords) REFERENCES ca_keywords (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_category_translation_keywords ADD CONSTRAINT FK_D15FBE3717CA14DA FOREIGN KEY (idCategoryTranslations) REFERENCES ca_category_translations (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_addresses ADD CONSTRAINT FK_4165FE4893205E40 FOREIGN KEY (idAddresses) REFERENCES co_addresses (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_addresses ADD CONSTRAINT FK_4165FE48996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_contacts ADD CONSTRAINT FK_28C6CA0E2A75CE2A FOREIGN KEY (idPositions) REFERENCES co_positions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_account_contacts ADD CONSTRAINT FK_28C6CA0E60E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_contacts ADD CONSTRAINT FK_28C6CA0E996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14A6D4A8651 FOREIGN KEY (idContactsMain) REFERENCES co_contacts (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14AC9171171 FOREIGN KEY (idAccountsParent) REFERENCES co_accounts (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14AE48E9A13 FOREIGN KEY (logo) REFERENCES me_media (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14ADBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14A30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_account_urls ADD CONSTRAINT FK_ADF18382996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_urls ADD CONSTRAINT FK_ADF183825969693F FOREIGN KEY (idUrls) REFERENCES co_urls (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_phones ADD CONSTRAINT FK_918DA964996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_phones ADD CONSTRAINT FK_918DA9648039866F FOREIGN KEY (idPhones) REFERENCES co_phones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_emails ADD CONSTRAINT FK_3E246FC3996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_emails ADD CONSTRAINT FK_3E246FC32F9040C8 FOREIGN KEY (idEmails) REFERENCES co_emails (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_notes ADD CONSTRAINT FK_A3FBB24A996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_notes ADD CONSTRAINT FK_A3FBB24A16DFE591 FOREIGN KEY (idNotes) REFERENCES co_notes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_faxes ADD CONSTRAINT FK_7A4E77DC996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_faxes ADD CONSTRAINT FK_7A4E77DCCF6A2007 FOREIGN KEY (idFaxes) REFERENCES co_faxes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_social_media_profiles ADD CONSTRAINT FK_E06F75F5996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_social_media_profiles ADD CONSTRAINT FK_E06F75F5573F8344 FOREIGN KEY (idSocialMediaProfiles) REFERENCES co_social_media_profiles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_bank_accounts ADD CONSTRAINT FK_C873A532996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_bank_accounts ADD CONSTRAINT FK_C873A53237FCD1D8 FOREIGN KEY (idBankAccounts) REFERENCES co_bank_account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_categories ADD CONSTRAINT FK_B60E9510996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_categories ADD CONSTRAINT FK_B60E9510B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_medias ADD CONSTRAINT FK_60772810996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_medias ADD CONSTRAINT FK_6077281071C3071B FOREIGN KEY (idMedias) REFERENCES me_media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_tags ADD CONSTRAINT FK_E8D92005996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_tags ADD CONSTRAINT FK_E8D920051C41CAB8 FOREIGN KEY (idTags) REFERENCES ta_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_addresses ADD CONSTRAINT FK_26E9A6142A37021A FOREIGN KEY (idAdressTypes) REFERENCES co_address_types (id)');
        $this->addSql('ALTER TABLE co_contact_addresses ADD CONSTRAINT FK_DEE056893205E40 FOREIGN KEY (idAddresses) REFERENCES co_addresses (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_addresses ADD CONSTRAINT FK_DEE056860E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_locales ADD CONSTRAINT FK_31E5672760E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id)');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A95A254E939 FOREIGN KEY (idTitles) REFERENCES co_contact_titles (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A951677722F FOREIGN KEY (avatar) REFERENCES me_media (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A95DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A9530D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_contact_urls ADD CONSTRAINT FK_99D86D760E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_urls ADD CONSTRAINT FK_99D86D75969693F FOREIGN KEY (idUrls) REFERENCES co_urls (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_notes ADD CONSTRAINT FK_B85E7B3460E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_notes ADD CONSTRAINT FK_B85E7B3416DFE591 FOREIGN KEY (idNotes) REFERENCES co_notes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_emails ADD CONSTRAINT FK_8982963160E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_emails ADD CONSTRAINT FK_898296312F9040C8 FOREIGN KEY (idEmails) REFERENCES co_emails (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_phones ADD CONSTRAINT FK_262B509660E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_phones ADD CONSTRAINT FK_262B50968039866F FOREIGN KEY (idPhones) REFERENCES co_phones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_faxes ADD CONSTRAINT FK_61EBBEA260E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_faxes ADD CONSTRAINT FK_61EBBEA2CF6A2007 FOREIGN KEY (idFaxes) REFERENCES co_faxes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles ADD CONSTRAINT FK_74FF4CC060E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles ADD CONSTRAINT FK_74FF4CC0573F8344 FOREIGN KEY (idSocialMediaProfiles) REFERENCES co_social_media_profiles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_bank_accounts ADD CONSTRAINT FK_76CDDA0660E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_bank_accounts ADD CONSTRAINT FK_76CDDA0637FCD1D8 FOREIGN KEY (idBankAccounts) REFERENCES co_bank_account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_medias ADD CONSTRAINT FK_D7D1D1E260E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_medias ADD CONSTRAINT FK_D7D1D1E271C3071B FOREIGN KEY (idMedias) REFERENCES me_media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_categories ADD CONSTRAINT FK_8D2C3E2360E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_categories ADD CONSTRAINT FK_8D2C3E23B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_tags ADD CONSTRAINT FK_4CB5255060E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_tags ADD CONSTRAINT FK_4CB525501C41CAB8 FOREIGN KEY (idTags) REFERENCES ta_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_emails ADD CONSTRAINT FK_A2F2CB77D816E840 FOREIGN KEY (idEmailTypes) REFERENCES co_email_types (id)');
        $this->addSql('ALTER TABLE co_faxes ADD CONSTRAINT FK_A5EC6A18B466C5DA FOREIGN KEY (idFaxTypes) REFERENCES co_fax_types (id)');
        $this->addSql('ALTER TABLE co_phones ADD CONSTRAINT FK_D5B0DD0A4249AD7 FOREIGN KEY (idPhoneTypes) REFERENCES co_phone_types (id)');
        $this->addSql('ALTER TABLE co_social_media_profiles ADD CONSTRAINT FK_DF585BFBB5BEA95F FOREIGN KEY (idSocialMediaTypes) REFERENCES co_social_media_profile_types (id)');
        $this->addSql('ALTER TABLE co_urls ADD CONSTRAINT FK_6F03842E882335CC FOREIGN KEY (idUrlTypes) REFERENCES co_url_types (id)');
        $this->addSql('ALTER TABLE cu_custom_url ADD CONSTRAINT FK_51A7F98DDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE cu_custom_url ADD CONSTRAINT FK_51A7F98D30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE cu_custom_url_route ADD CONSTRAINT FK_D2349CF4CB30A644 FOREIGN KEY (customUrl) REFERENCES cu_custom_url (uuid) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cu_custom_url_route ADD CONSTRAINT FK_D2349CF44ED689B2 FOREIGN KEY (target_route_uuid) REFERENCES cu_custom_url_route (uuid) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_collection_meta ADD CONSTRAINT FK_F8D5E71693782C96 FOREIGN KEY (idCollections) REFERENCES me_collections (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887CFA3F467 FOREIGN KEY (idCollectionsMetaDefault) REFERENCES me_collection_meta (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887E67924D6 FOREIGN KEY (idCollectionTypes) REFERENCES me_collection_types (id)');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887A4F2DCF8 FOREIGN KEY (idCollectionsParent) REFERENCES me_collections (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D488730D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_file_version_meta ADD CONSTRAINT FK_AD44B0AD911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E89456B801096 FOREIGN KEY (idFileVersionsMetaDefault) REFERENCES me_file_version_meta (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E894511F10344 FOREIGN KEY (idFiles) REFERENCES me_files (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E8945DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E894530D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_file_version_tags ADD CONSTRAINT FK_150A30BE911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_version_tags ADD CONSTRAINT FK_150A30BE1C41CAB8 FOREIGN KEY (idTags) REFERENCES ta_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_version_categories ADD CONSTRAINT FK_2F1E17D0911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_version_categories ADD CONSTRAINT FK_2F1E17D0B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_files ADD CONSTRAINT FK_CA8D04277DE8E211 FOREIGN KEY (idMedia) REFERENCES me_media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_files ADD CONSTRAINT FK_CA8D0427DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_files ADD CONSTRAINT FK_CA8D042730D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_format_options ADD CONSTRAINT FK_6D25443B31852B63 FOREIGN KEY (fileVersion) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E572D1EB44DE FOREIGN KEY (idPreviewImage) REFERENCES me_media (id)');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E57293782C96 FOREIGN KEY (idCollections) REFERENCES me_collections (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E572DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E57230D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pa_page_dimension_content_navigation_contexts ADD CONSTRAINT FK_4C5FD8F767C2CFD5 FOREIGN KEY (page_dimension_content_id) REFERENCES pa_page_dimension_contents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pa_page_dimension_contents ADD CONSTRAINT FK_209A42C034ECB4E6 FOREIGN KEY (route_id) REFERENCES ro_routes (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pa_page_dimension_contents ADD CONSTRAINT FK_209A42C0F099EEF3 FOREIGN KEY (pageUuid) REFERENCES pa_pages (uuid) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pa_page_dimension_contents ADD CONSTRAINT FK_209A42C0F675F31B FOREIGN KEY (author_id) REFERENCES co_contacts (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pa_page_dimension_contents ADD CONSTRAINT FK_209A42C0DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pa_page_dimension_contents ADD CONSTRAINT FK_209A42C030D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pa_page_dimension_content_excerpt_tags ADD CONSTRAINT FK_66C81FDB67C2CFD5 FOREIGN KEY (page_dimension_content_id) REFERENCES pa_page_dimension_contents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pa_page_dimension_content_excerpt_tags ADD CONSTRAINT FK_66C81FDBBAD26311 FOREIGN KEY (tag_id) REFERENCES ta_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pa_page_dimension_content_excerpt_categories ADD CONSTRAINT FK_BE45C16867C2CFD5 FOREIGN KEY (page_dimension_content_id) REFERENCES pa_page_dimension_contents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pa_page_dimension_content_excerpt_categories ADD CONSTRAINT FK_BE45C16812469DE2 FOREIGN KEY (category_id) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pa_pages ADD CONSTRAINT FK_FF3DA1E2727ACA70 FOREIGN KEY (parent_id) REFERENCES pa_pages (uuid) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pa_pages ADD CONSTRAINT FK_FF3DA1E2DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pa_pages ADD CONSTRAINT FK_FF3DA1E230D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ro_routes ADD CONSTRAINT FK_671DB7A4727ACA70 FOREIGN KEY (parent_id) REFERENCES ro_routes (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_access_controls ADD CONSTRAINT FK_C526DC52A1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_permissions ADD CONSTRAINT FK_5CEC3EEAA1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_role_settings ADD CONSTRAINT FK_DAD1C8CBB8C2FD88 FOREIGN KEY (roleId) REFERENCES se_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_roles ADD CONSTRAINT FK_13B749A0DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_roles ADD CONSTRAINT FK_13B749A030D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_user_roles ADD CONSTRAINT FK_E48BD9DB347E6F4 FOREIGN KEY (idUsers) REFERENCES se_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_user_roles ADD CONSTRAINT FK_E48BD9DBA1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_user_settings ADD CONSTRAINT FK_108FCAFA347E6F4 FOREIGN KEY (idUsers) REFERENCES se_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_user_two_factors ADD CONSTRAINT FK_732E8321347E6F4 FOREIGN KEY (idUsers) REFERENCES se_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_users ADD CONSTRAINT FK_B10AC28E60E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_users ADD CONSTRAINT FK_B10AC28EDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_users ADD CONSTRAINT FK_B10AC28E30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sn_snippet_area ADD CONSTRAINT FK_8C978EE186A5E727 FOREIGN KEY (idSnippet) REFERENCES sn_snippets (uuid) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sn_snippet_dimension_contents ADD CONSTRAINT FK_46D6814477F33FFB FOREIGN KEY (snippetUuid) REFERENCES sn_snippets (uuid) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sn_snippet_dimension_contents ADD CONSTRAINT FK_46D68144DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sn_snippet_dimension_contents ADD CONSTRAINT FK_46D6814430D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sn_snippet_dimension_content_excerpt_tags ADD CONSTRAINT FK_96BD1E357891499D FOREIGN KEY (snippet_dimension_content_id) REFERENCES sn_snippet_dimension_contents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sn_snippet_dimension_content_excerpt_tags ADD CONSTRAINT FK_96BD1E35BAD26311 FOREIGN KEY (tag_id) REFERENCES ta_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sn_snippet_dimension_content_excerpt_categories ADD CONSTRAINT FK_464EB1547891499D FOREIGN KEY (snippet_dimension_content_id) REFERENCES sn_snippet_dimension_contents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sn_snippet_dimension_content_excerpt_categories ADD CONSTRAINT FK_464EB15412469DE2 FOREIGN KEY (category_id) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sn_snippets ADD CONSTRAINT FK_E68115CFDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sn_snippets ADD CONSTRAINT FK_E68115CF30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ta_tags ADD CONSTRAINT FK_B258E499DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ta_tags ADD CONSTRAINT FK_B258E49930D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE tr_trash_item_translations ADD CONSTRAINT FK_8264DAF45C8D7CA FOREIGN KEY (trashItemId) REFERENCES tr_trash_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tr_trash_items ADD CONSTRAINT FK_102989B64B64DCC FOREIGN KEY (userId) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE we_analytics_domains ADD CONSTRAINT FK_F9323B6EEAC2E688 FOREIGN KEY (analytics) REFERENCES we_analytics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE we_analytics_domains ADD CONSTRAINT FK_F9323B6EA7A91E0B FOREIGN KEY (domain) REFERENCES we_domains (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ac_activities DROP FOREIGN KEY FK_3EE015D064B64DCC');
        $this->addSql('ALTER TABLE ar_article_dimension_content_additional_webspaces DROP FOREIGN KEY FK_3F9F33F37C1747D1');
        $this->addSql('ALTER TABLE ar_article_dimension_contents DROP FOREIGN KEY FK_5674F7BF34ECB4E6');
        $this->addSql('ALTER TABLE ar_article_dimension_contents DROP FOREIGN KEY FK_5674F7BFAE39C518');
        $this->addSql('ALTER TABLE ar_article_dimension_contents DROP FOREIGN KEY FK_5674F7BFF675F31B');
        $this->addSql('ALTER TABLE ar_article_dimension_contents DROP FOREIGN KEY FK_5674F7BFDBF11E1D');
        $this->addSql('ALTER TABLE ar_article_dimension_contents DROP FOREIGN KEY FK_5674F7BF30D07CD5');
        $this->addSql('ALTER TABLE ar_article_dimension_content_excerpt_tags DROP FOREIGN KEY FK_B45854027C1747D1');
        $this->addSql('ALTER TABLE ar_article_dimension_content_excerpt_tags DROP FOREIGN KEY FK_B4585402BAD26311');
        $this->addSql('ALTER TABLE ar_article_dimension_content_excerpt_categories DROP FOREIGN KEY FK_971AE52D7C1747D1');
        $this->addSql('ALTER TABLE ar_article_dimension_content_excerpt_categories DROP FOREIGN KEY FK_971AE52D12469DE2');
        $this->addSql('ALTER TABLE ar_articles DROP FOREIGN KEY FK_7F75CD17DBF11E1D');
        $this->addSql('ALTER TABLE ar_articles DROP FOREIGN KEY FK_7F75CD1730D07CD5');
        $this->addSql('ALTER TABLE ca_categories DROP FOREIGN KEY FK_3D85D78937A3C3B1');
        $this->addSql('ALTER TABLE ca_categories DROP FOREIGN KEY FK_3D85D789DBF11E1D');
        $this->addSql('ALTER TABLE ca_categories DROP FOREIGN KEY FK_3D85D78930D07CD5');
        $this->addSql('ALTER TABLE ca_category_translation_medias DROP FOREIGN KEY FK_39FC41BA17CA14DA');
        $this->addSql('ALTER TABLE ca_category_translation_medias DROP FOREIGN KEY FK_39FC41BA7DE8E211');
        $this->addSql('ALTER TABLE ca_category_translations DROP FOREIGN KEY FK_5DCED5E3B8075882');
        $this->addSql('ALTER TABLE ca_category_translations DROP FOREIGN KEY FK_5DCED5E3DBF11E1D');
        $this->addSql('ALTER TABLE ca_category_translations DROP FOREIGN KEY FK_5DCED5E330D07CD5');
        $this->addSql('ALTER TABLE ca_keywords DROP FOREIGN KEY FK_FE02CA0BDBF11E1D');
        $this->addSql('ALTER TABLE ca_keywords DROP FOREIGN KEY FK_FE02CA0B30D07CD5');
        $this->addSql('ALTER TABLE ca_category_translation_keywords DROP FOREIGN KEY FK_D15FBE37F9FC9F05');
        $this->addSql('ALTER TABLE ca_category_translation_keywords DROP FOREIGN KEY FK_D15FBE3717CA14DA');
        $this->addSql('ALTER TABLE co_account_addresses DROP FOREIGN KEY FK_4165FE4893205E40');
        $this->addSql('ALTER TABLE co_account_addresses DROP FOREIGN KEY FK_4165FE48996BB4F7');
        $this->addSql('ALTER TABLE co_account_contacts DROP FOREIGN KEY FK_28C6CA0E2A75CE2A');
        $this->addSql('ALTER TABLE co_account_contacts DROP FOREIGN KEY FK_28C6CA0E60E33F28');
        $this->addSql('ALTER TABLE co_account_contacts DROP FOREIGN KEY FK_28C6CA0E996BB4F7');
        $this->addSql('ALTER TABLE co_accounts DROP FOREIGN KEY FK_805CD14A6D4A8651');
        $this->addSql('ALTER TABLE co_accounts DROP FOREIGN KEY FK_805CD14AC9171171');
        $this->addSql('ALTER TABLE co_accounts DROP FOREIGN KEY FK_805CD14AE48E9A13');
        $this->addSql('ALTER TABLE co_accounts DROP FOREIGN KEY FK_805CD14ADBF11E1D');
        $this->addSql('ALTER TABLE co_accounts DROP FOREIGN KEY FK_805CD14A30D07CD5');
        $this->addSql('ALTER TABLE co_account_urls DROP FOREIGN KEY FK_ADF18382996BB4F7');
        $this->addSql('ALTER TABLE co_account_urls DROP FOREIGN KEY FK_ADF183825969693F');
        $this->addSql('ALTER TABLE co_account_phones DROP FOREIGN KEY FK_918DA964996BB4F7');
        $this->addSql('ALTER TABLE co_account_phones DROP FOREIGN KEY FK_918DA9648039866F');
        $this->addSql('ALTER TABLE co_account_emails DROP FOREIGN KEY FK_3E246FC3996BB4F7');
        $this->addSql('ALTER TABLE co_account_emails DROP FOREIGN KEY FK_3E246FC32F9040C8');
        $this->addSql('ALTER TABLE co_account_notes DROP FOREIGN KEY FK_A3FBB24A996BB4F7');
        $this->addSql('ALTER TABLE co_account_notes DROP FOREIGN KEY FK_A3FBB24A16DFE591');
        $this->addSql('ALTER TABLE co_account_faxes DROP FOREIGN KEY FK_7A4E77DC996BB4F7');
        $this->addSql('ALTER TABLE co_account_faxes DROP FOREIGN KEY FK_7A4E77DCCF6A2007');
        $this->addSql('ALTER TABLE co_account_social_media_profiles DROP FOREIGN KEY FK_E06F75F5996BB4F7');
        $this->addSql('ALTER TABLE co_account_social_media_profiles DROP FOREIGN KEY FK_E06F75F5573F8344');
        $this->addSql('ALTER TABLE co_account_bank_accounts DROP FOREIGN KEY FK_C873A532996BB4F7');
        $this->addSql('ALTER TABLE co_account_bank_accounts DROP FOREIGN KEY FK_C873A53237FCD1D8');
        $this->addSql('ALTER TABLE co_account_categories DROP FOREIGN KEY FK_B60E9510996BB4F7');
        $this->addSql('ALTER TABLE co_account_categories DROP FOREIGN KEY FK_B60E9510B8075882');
        $this->addSql('ALTER TABLE co_account_medias DROP FOREIGN KEY FK_60772810996BB4F7');
        $this->addSql('ALTER TABLE co_account_medias DROP FOREIGN KEY FK_6077281071C3071B');
        $this->addSql('ALTER TABLE co_account_tags DROP FOREIGN KEY FK_E8D92005996BB4F7');
        $this->addSql('ALTER TABLE co_account_tags DROP FOREIGN KEY FK_E8D920051C41CAB8');
        $this->addSql('ALTER TABLE co_addresses DROP FOREIGN KEY FK_26E9A6142A37021A');
        $this->addSql('ALTER TABLE co_contact_addresses DROP FOREIGN KEY FK_DEE056893205E40');
        $this->addSql('ALTER TABLE co_contact_addresses DROP FOREIGN KEY FK_DEE056860E33F28');
        $this->addSql('ALTER TABLE co_contact_locales DROP FOREIGN KEY FK_31E5672760E33F28');
        $this->addSql('ALTER TABLE co_contacts DROP FOREIGN KEY FK_79D45A95A254E939');
        $this->addSql('ALTER TABLE co_contacts DROP FOREIGN KEY FK_79D45A951677722F');
        $this->addSql('ALTER TABLE co_contacts DROP FOREIGN KEY FK_79D45A95DBF11E1D');
        $this->addSql('ALTER TABLE co_contacts DROP FOREIGN KEY FK_79D45A9530D07CD5');
        $this->addSql('ALTER TABLE co_contact_urls DROP FOREIGN KEY FK_99D86D760E33F28');
        $this->addSql('ALTER TABLE co_contact_urls DROP FOREIGN KEY FK_99D86D75969693F');
        $this->addSql('ALTER TABLE co_contact_notes DROP FOREIGN KEY FK_B85E7B3460E33F28');
        $this->addSql('ALTER TABLE co_contact_notes DROP FOREIGN KEY FK_B85E7B3416DFE591');
        $this->addSql('ALTER TABLE co_contact_emails DROP FOREIGN KEY FK_8982963160E33F28');
        $this->addSql('ALTER TABLE co_contact_emails DROP FOREIGN KEY FK_898296312F9040C8');
        $this->addSql('ALTER TABLE co_contact_phones DROP FOREIGN KEY FK_262B509660E33F28');
        $this->addSql('ALTER TABLE co_contact_phones DROP FOREIGN KEY FK_262B50968039866F');
        $this->addSql('ALTER TABLE co_contact_faxes DROP FOREIGN KEY FK_61EBBEA260E33F28');
        $this->addSql('ALTER TABLE co_contact_faxes DROP FOREIGN KEY FK_61EBBEA2CF6A2007');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles DROP FOREIGN KEY FK_74FF4CC060E33F28');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles DROP FOREIGN KEY FK_74FF4CC0573F8344');
        $this->addSql('ALTER TABLE co_contact_bank_accounts DROP FOREIGN KEY FK_76CDDA0660E33F28');
        $this->addSql('ALTER TABLE co_contact_bank_accounts DROP FOREIGN KEY FK_76CDDA0637FCD1D8');
        $this->addSql('ALTER TABLE co_contact_medias DROP FOREIGN KEY FK_D7D1D1E260E33F28');
        $this->addSql('ALTER TABLE co_contact_medias DROP FOREIGN KEY FK_D7D1D1E271C3071B');
        $this->addSql('ALTER TABLE co_contact_categories DROP FOREIGN KEY FK_8D2C3E2360E33F28');
        $this->addSql('ALTER TABLE co_contact_categories DROP FOREIGN KEY FK_8D2C3E23B8075882');
        $this->addSql('ALTER TABLE co_contact_tags DROP FOREIGN KEY FK_4CB5255060E33F28');
        $this->addSql('ALTER TABLE co_contact_tags DROP FOREIGN KEY FK_4CB525501C41CAB8');
        $this->addSql('ALTER TABLE co_emails DROP FOREIGN KEY FK_A2F2CB77D816E840');
        $this->addSql('ALTER TABLE co_faxes DROP FOREIGN KEY FK_A5EC6A18B466C5DA');
        $this->addSql('ALTER TABLE co_phones DROP FOREIGN KEY FK_D5B0DD0A4249AD7');
        $this->addSql('ALTER TABLE co_social_media_profiles DROP FOREIGN KEY FK_DF585BFBB5BEA95F');
        $this->addSql('ALTER TABLE co_urls DROP FOREIGN KEY FK_6F03842E882335CC');
        $this->addSql('ALTER TABLE cu_custom_url DROP FOREIGN KEY FK_51A7F98DDBF11E1D');
        $this->addSql('ALTER TABLE cu_custom_url DROP FOREIGN KEY FK_51A7F98D30D07CD5');
        $this->addSql('ALTER TABLE cu_custom_url_route DROP FOREIGN KEY FK_D2349CF4CB30A644');
        $this->addSql('ALTER TABLE cu_custom_url_route DROP FOREIGN KEY FK_D2349CF44ED689B2');
        $this->addSql('ALTER TABLE me_collection_meta DROP FOREIGN KEY FK_F8D5E71693782C96');
        $this->addSql('ALTER TABLE me_collections DROP FOREIGN KEY FK_F0D4887CFA3F467');
        $this->addSql('ALTER TABLE me_collections DROP FOREIGN KEY FK_F0D4887E67924D6');
        $this->addSql('ALTER TABLE me_collections DROP FOREIGN KEY FK_F0D4887A4F2DCF8');
        $this->addSql('ALTER TABLE me_collections DROP FOREIGN KEY FK_F0D4887DBF11E1D');
        $this->addSql('ALTER TABLE me_collections DROP FOREIGN KEY FK_F0D488730D07CD5');
        $this->addSql('ALTER TABLE me_file_version_meta DROP FOREIGN KEY FK_AD44B0AD911ADE33');
        $this->addSql('ALTER TABLE me_file_versions DROP FOREIGN KEY FK_7B6E89456B801096');
        $this->addSql('ALTER TABLE me_file_versions DROP FOREIGN KEY FK_7B6E894511F10344');
        $this->addSql('ALTER TABLE me_file_versions DROP FOREIGN KEY FK_7B6E8945DBF11E1D');
        $this->addSql('ALTER TABLE me_file_versions DROP FOREIGN KEY FK_7B6E894530D07CD5');
        $this->addSql('ALTER TABLE me_file_version_tags DROP FOREIGN KEY FK_150A30BE911ADE33');
        $this->addSql('ALTER TABLE me_file_version_tags DROP FOREIGN KEY FK_150A30BE1C41CAB8');
        $this->addSql('ALTER TABLE me_file_version_categories DROP FOREIGN KEY FK_2F1E17D0911ADE33');
        $this->addSql('ALTER TABLE me_file_version_categories DROP FOREIGN KEY FK_2F1E17D0B8075882');
        $this->addSql('ALTER TABLE me_files DROP FOREIGN KEY FK_CA8D04277DE8E211');
        $this->addSql('ALTER TABLE me_files DROP FOREIGN KEY FK_CA8D0427DBF11E1D');
        $this->addSql('ALTER TABLE me_files DROP FOREIGN KEY FK_CA8D042730D07CD5');
        $this->addSql('ALTER TABLE me_format_options DROP FOREIGN KEY FK_6D25443B31852B63');
        $this->addSql('ALTER TABLE me_media DROP FOREIGN KEY FK_A694E572D1EB44DE');
        $this->addSql('ALTER TABLE me_media DROP FOREIGN KEY FK_A694E57293782C96');
        $this->addSql('ALTER TABLE me_media DROP FOREIGN KEY FK_A694E572DBF11E1D');
        $this->addSql('ALTER TABLE me_media DROP FOREIGN KEY FK_A694E57230D07CD5');
        $this->addSql('ALTER TABLE pa_page_dimension_content_navigation_contexts DROP FOREIGN KEY FK_4C5FD8F767C2CFD5');
        $this->addSql('ALTER TABLE pa_page_dimension_contents DROP FOREIGN KEY FK_209A42C034ECB4E6');
        $this->addSql('ALTER TABLE pa_page_dimension_contents DROP FOREIGN KEY FK_209A42C0F099EEF3');
        $this->addSql('ALTER TABLE pa_page_dimension_contents DROP FOREIGN KEY FK_209A42C0F675F31B');
        $this->addSql('ALTER TABLE pa_page_dimension_contents DROP FOREIGN KEY FK_209A42C0DBF11E1D');
        $this->addSql('ALTER TABLE pa_page_dimension_contents DROP FOREIGN KEY FK_209A42C030D07CD5');
        $this->addSql('ALTER TABLE pa_page_dimension_content_excerpt_tags DROP FOREIGN KEY FK_66C81FDB67C2CFD5');
        $this->addSql('ALTER TABLE pa_page_dimension_content_excerpt_tags DROP FOREIGN KEY FK_66C81FDBBAD26311');
        $this->addSql('ALTER TABLE pa_page_dimension_content_excerpt_categories DROP FOREIGN KEY FK_BE45C16867C2CFD5');
        $this->addSql('ALTER TABLE pa_page_dimension_content_excerpt_categories DROP FOREIGN KEY FK_BE45C16812469DE2');
        $this->addSql('ALTER TABLE pa_pages DROP FOREIGN KEY FK_FF3DA1E2727ACA70');
        $this->addSql('ALTER TABLE pa_pages DROP FOREIGN KEY FK_FF3DA1E2DBF11E1D');
        $this->addSql('ALTER TABLE pa_pages DROP FOREIGN KEY FK_FF3DA1E230D07CD5');
        $this->addSql('ALTER TABLE ro_routes DROP FOREIGN KEY FK_671DB7A4727ACA70');
        $this->addSql('ALTER TABLE se_access_controls DROP FOREIGN KEY FK_C526DC52A1FA6DDA');
        $this->addSql('ALTER TABLE se_permissions DROP FOREIGN KEY FK_5CEC3EEAA1FA6DDA');
        $this->addSql('ALTER TABLE se_role_settings DROP FOREIGN KEY FK_DAD1C8CBB8C2FD88');
        $this->addSql('ALTER TABLE se_roles DROP FOREIGN KEY FK_13B749A0DBF11E1D');
        $this->addSql('ALTER TABLE se_roles DROP FOREIGN KEY FK_13B749A030D07CD5');
        $this->addSql('ALTER TABLE se_user_roles DROP FOREIGN KEY FK_E48BD9DB347E6F4');
        $this->addSql('ALTER TABLE se_user_roles DROP FOREIGN KEY FK_E48BD9DBA1FA6DDA');
        $this->addSql('ALTER TABLE se_user_settings DROP FOREIGN KEY FK_108FCAFA347E6F4');
        $this->addSql('ALTER TABLE se_user_two_factors DROP FOREIGN KEY FK_732E8321347E6F4');
        $this->addSql('ALTER TABLE se_users DROP FOREIGN KEY FK_B10AC28E60E33F28');
        $this->addSql('ALTER TABLE se_users DROP FOREIGN KEY FK_B10AC28EDBF11E1D');
        $this->addSql('ALTER TABLE se_users DROP FOREIGN KEY FK_B10AC28E30D07CD5');
        $this->addSql('ALTER TABLE sn_snippet_area DROP FOREIGN KEY FK_8C978EE186A5E727');
        $this->addSql('ALTER TABLE sn_snippet_dimension_contents DROP FOREIGN KEY FK_46D6814477F33FFB');
        $this->addSql('ALTER TABLE sn_snippet_dimension_contents DROP FOREIGN KEY FK_46D68144DBF11E1D');
        $this->addSql('ALTER TABLE sn_snippet_dimension_contents DROP FOREIGN KEY FK_46D6814430D07CD5');
        $this->addSql('ALTER TABLE sn_snippet_dimension_content_excerpt_tags DROP FOREIGN KEY FK_96BD1E357891499D');
        $this->addSql('ALTER TABLE sn_snippet_dimension_content_excerpt_tags DROP FOREIGN KEY FK_96BD1E35BAD26311');
        $this->addSql('ALTER TABLE sn_snippet_dimension_content_excerpt_categories DROP FOREIGN KEY FK_464EB1547891499D');
        $this->addSql('ALTER TABLE sn_snippet_dimension_content_excerpt_categories DROP FOREIGN KEY FK_464EB15412469DE2');
        $this->addSql('ALTER TABLE sn_snippets DROP FOREIGN KEY FK_E68115CFDBF11E1D');
        $this->addSql('ALTER TABLE sn_snippets DROP FOREIGN KEY FK_E68115CF30D07CD5');
        $this->addSql('ALTER TABLE ta_tags DROP FOREIGN KEY FK_B258E499DBF11E1D');
        $this->addSql('ALTER TABLE ta_tags DROP FOREIGN KEY FK_B258E49930D07CD5');
        $this->addSql('ALTER TABLE tr_trash_item_translations DROP FOREIGN KEY FK_8264DAF45C8D7CA');
        $this->addSql('ALTER TABLE tr_trash_items DROP FOREIGN KEY FK_102989B64B64DCC');
        $this->addSql('ALTER TABLE we_analytics_domains DROP FOREIGN KEY FK_F9323B6EEAC2E688');
        $this->addSql('ALTER TABLE we_analytics_domains DROP FOREIGN KEY FK_F9323B6EA7A91E0B');
        $this->addSql('DROP TABLE ac_activities');
        $this->addSql('DROP TABLE ar_article_dimension_content_additional_webspaces');
        $this->addSql('DROP TABLE ar_article_dimension_contents');
        $this->addSql('DROP TABLE ar_article_dimension_content_excerpt_tags');
        $this->addSql('DROP TABLE ar_article_dimension_content_excerpt_categories');
        $this->addSql('DROP TABLE ar_articles');
        $this->addSql('DROP TABLE ca_categories');
        $this->addSql('DROP TABLE ca_category_translation_medias');
        $this->addSql('DROP TABLE ca_category_translations');
        $this->addSql('DROP TABLE ca_keywords');
        $this->addSql('DROP TABLE ca_category_translation_keywords');
        $this->addSql('DROP TABLE co_account_addresses');
        $this->addSql('DROP TABLE co_account_contacts');
        $this->addSql('DROP TABLE co_accounts');
        $this->addSql('DROP TABLE co_account_urls');
        $this->addSql('DROP TABLE co_account_phones');
        $this->addSql('DROP TABLE co_account_emails');
        $this->addSql('DROP TABLE co_account_notes');
        $this->addSql('DROP TABLE co_account_faxes');
        $this->addSql('DROP TABLE co_account_social_media_profiles');
        $this->addSql('DROP TABLE co_account_bank_accounts');
        $this->addSql('DROP TABLE co_account_categories');
        $this->addSql('DROP TABLE co_account_medias');
        $this->addSql('DROP TABLE co_account_tags');
        $this->addSql('DROP TABLE co_address_types');
        $this->addSql('DROP TABLE co_addresses');
        $this->addSql('DROP TABLE co_bank_account');
        $this->addSql('DROP TABLE co_contact_addresses');
        $this->addSql('DROP TABLE co_contact_locales');
        $this->addSql('DROP TABLE co_contact_titles');
        $this->addSql('DROP TABLE co_contacts');
        $this->addSql('DROP TABLE co_contact_urls');
        $this->addSql('DROP TABLE co_contact_notes');
        $this->addSql('DROP TABLE co_contact_emails');
        $this->addSql('DROP TABLE co_contact_phones');
        $this->addSql('DROP TABLE co_contact_faxes');
        $this->addSql('DROP TABLE co_contact_social_media_profiles');
        $this->addSql('DROP TABLE co_contact_bank_accounts');
        $this->addSql('DROP TABLE co_contact_medias');
        $this->addSql('DROP TABLE co_contact_categories');
        $this->addSql('DROP TABLE co_contact_tags');
        $this->addSql('DROP TABLE co_email_types');
        $this->addSql('DROP TABLE co_emails');
        $this->addSql('DROP TABLE co_fax_types');
        $this->addSql('DROP TABLE co_faxes');
        $this->addSql('DROP TABLE co_notes');
        $this->addSql('DROP TABLE co_phone_types');
        $this->addSql('DROP TABLE co_phones');
        $this->addSql('DROP TABLE co_positions');
        $this->addSql('DROP TABLE co_social_media_profile_types');
        $this->addSql('DROP TABLE co_social_media_profiles');
        $this->addSql('DROP TABLE co_url_types');
        $this->addSql('DROP TABLE co_urls');
        $this->addSql('DROP TABLE cu_custom_url');
        $this->addSql('DROP TABLE cu_custom_url_route');
        $this->addSql('DROP TABLE me_collection_meta');
        $this->addSql('DROP TABLE me_collection_types');
        $this->addSql('DROP TABLE me_collections');
        $this->addSql('DROP TABLE me_file_version_meta');
        $this->addSql('DROP TABLE me_file_versions');
        $this->addSql('DROP TABLE me_file_version_tags');
        $this->addSql('DROP TABLE me_file_version_categories');
        $this->addSql('DROP TABLE me_files');
        $this->addSql('DROP TABLE me_format_options');
        $this->addSql('DROP TABLE me_media');
        $this->addSql('DROP TABLE pa_page_dimension_content_navigation_contexts');
        $this->addSql('DROP TABLE pa_page_dimension_contents');
        $this->addSql('DROP TABLE pa_page_dimension_content_excerpt_tags');
        $this->addSql('DROP TABLE pa_page_dimension_content_excerpt_categories');
        $this->addSql('DROP TABLE pa_pages');
        $this->addSql('DROP TABLE pr_preview_links');
        $this->addSql('DROP TABLE re_references');
        $this->addSql('DROP TABLE ro_routes');
        $this->addSql('DROP TABLE se_access_controls');
        $this->addSql('DROP TABLE se_permissions');
        $this->addSql('DROP TABLE se_role_settings');
        $this->addSql('DROP TABLE se_roles');
        $this->addSql('DROP TABLE se_user_roles');
        $this->addSql('DROP TABLE se_user_settings');
        $this->addSql('DROP TABLE se_user_two_factors');
        $this->addSql('DROP TABLE se_users');
        $this->addSql('DROP TABLE sn_snippet_area');
        $this->addSql('DROP TABLE sn_snippet_dimension_contents');
        $this->addSql('DROP TABLE sn_snippet_dimension_content_excerpt_tags');
        $this->addSql('DROP TABLE sn_snippet_dimension_content_excerpt_categories');
        $this->addSql('DROP TABLE sn_snippets');
        $this->addSql('DROP TABLE ta_tags');
        $this->addSql('DROP TABLE tr_trash_item_translations');
        $this->addSql('DROP TABLE tr_trash_items');
        $this->addSql('DROP TABLE we_analytics');
        $this->addSql('DROP TABLE we_analytics_domains');
        $this->addSql('DROP TABLE we_domains');
    }
}
